# Generated by Django 2.2.3 on 2019-10-12 10:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Department'), (1, 'Clubs'), (2, 'placements'), (3, 'fests'), (4, 'hostel'), (5, 'general')], default=0, max_length=11)),
                ('email', models.EmailField(max_length=70)),
                ('first_name', models.DateTimeField(max_length=30)),
                ('last_name', models.IntegerField(max_length=30)),
            ],
        ),
    ]
