# Generated by Django 2.2.3 on 2019-10-12 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20191012_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='userfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Department'), (1, 'Clubs'), (2, 'placements'), (3, 'fests'), (4, 'hostel'), (5, 'general')], default=0, max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
