# Generated by Django 2.2.3 on 2019-10-12 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20191012_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UwerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.IntegerField(choices=[(0, 'Department'), (1, 'Clubs'), (2, 'placements'), (3, 'fests'), (4, 'hostel'), (5, 'general')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='userfield',
        ),
    ]
