# Generated by Django 2.2.3 on 2019-10-12 16:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191012_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Department'), (1, 'Clubs'), (2, 'placements'), (3, 'fests'), (4, 'hostel'), (5, 'general')], default=0, max_length=11),
        ),
    ]
