# Generated by Django 2.2 on 2020-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191012_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
