# Generated by Django 2.2.3 on 2019-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Answered'), (1, 'Answered')], default=0),
        ),
    ]
