# Generated by Django 2.2 on 2020-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
