# Generated by Django 2.2 on 2020-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200115_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
