# Generated by Django 2.2 on 2020-01-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200117_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
