# Generated by Django 2.2 on 2020-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='User',
        ),
        migrations.AddField(
            model_name='notifications',
            name='whom',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
