# Generated by Django 2.2 on 2020-01-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_ansvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_on']},
        ),
    ]
