# Generated by Django 2.2 on 2020-01-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200119_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Answer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Answer'),
            preserve_default=False,
        ),
    ]
