# Generated by Django 2.2 on 2020-01-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_notifications_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='Answer',
        ),
    ]
