# Generated by Django 2.2 on 2020-01-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_notifications_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='Answer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='blog.Answer'),
            preserve_default=False,
        ),
    ]
