# Generated by Django 2.2 on 2020-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200429_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=11),
        ),
    ]
